--- #YAML:1.0
name:               MojoX-Auth-Simple
version:            0.04
abstract:           Perl extension for simple login authentication for Mojolicious web applications
author:
    - Kim Hawtin <kim@hawtin.net.au>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MojoX::Session 0
    Mojo:          0.999914
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4

